# Generated by Django 3.0.8 on 2020-07-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Designates whether a product active or not'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'seller')), models.Q(('app_label', 'accounts'), ('model', 'admin')), models.Q(('app_label', 'accounts'), ('model', 'moderator')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Type of user'),
        ),
    ]
