# Generated by Django 3.0.8 on 2020-08-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0002_auto_20200731_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_fabricator',
            field=models.CharField(default='ss', max_length=127, verbose_name='Fabricator of a product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'seller')), models.Q(('app_label', 'accounts'), ('model', 'admin')), models.Q(('app_label', 'accounts'), ('model', 'moderator')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='products', to='contenttypes.ContentType', verbose_name='Type of user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Id of a user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Slug (If no slug title will be slugified)'),
        ),
    ]
