# Generated by Django 3.0.8 on 2020-07-31 11:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120, verbose_name='Address line')),
                ('address_line_2', models.CharField(blank=True, max_length=120, verbose_name='Second address line (optional)')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country of a customer')),
                ('city', models.CharField(max_length=120, verbose_name='City of a customer')),
                ('state', models.CharField(max_length=120, verbose_name='State of a customer')),
                ('postal_code', models.CharField(max_length=120, verbose_name='Postal code of a customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_addresses', to='accounts.Seller')),
            ],
            options={
                'verbose_name': 'Seller Address',
                'verbose_name_plural': 'Seller Addresses',
                'ordering': ('seller',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120, verbose_name='Address line')),
                ('address_line_2', models.CharField(blank=True, max_length=120, verbose_name='Second address line (optional)')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country of a customer')),
                ('city', models.CharField(max_length=120, verbose_name='City of a customer')),
                ('state', models.CharField(max_length=120, verbose_name='State of a customer')),
                ('postal_code', models.CharField(max_length=120, verbose_name='Postal code of a customer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_addresses', to='accounts.Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('customer',),
            },
        ),
    ]
